from __future__ import annotations
from typing import TYPE_CHECKING
from BaseClasses import Region
if TYPE_CHECKING:
    from .world import FP2World

def create_and_connect_regions(world: FP2World) -> None:
    create_all_regions(world)
    connect_regions(world)

def create_all_regions(world: FP2World) -> None:
    # Create the menu and stage regions.
    menu = Region("Menu", world.player, world.multiworld)
    dValley = Region("Dragon Valley", world.player, world.multiworld)
    sPark = Region("Shenlin Park", world.player, world.multiworld)
    tFalls = Region("Tiger Falls", world.player, world.multiworld)
    rGraveyard = Region("Robot Graveyard", world.player, world.multiworld)
    sArmory = Region("Shade Armory", world.player, world.multiworld)
    snowfields = Region("Snowfields", world.player, world.multiworld)
    aMuseum = Region("Avian Museum", world.player, world.multiworld)
    aSigwada = Region("Airship Sigwada", world.player, world.multiworld)
    pHighway = Region("Phoenix Highway", world.player, world.multiworld)
    zLand = Region("Zao Land", world.player, world.multiworld)
    battlesphere = Region("The Battlesphere", world.player, world.multiworld)
    gOpera1 = Region("Globe Opera 1", world.player, world.multiworld)
    gOpera2 = Region("Globe Opera 2", world.player, world.multiworld)
    auditorium = Region("Auditorium", world.player, world.multiworld)
    pCourtyard = Region("Palace Courtyard", world.player, world.multiworld)
    tGate = Region("Tidal Gate", world.player, world.multiworld)
    sBridge = Region("Sky Bridge", world.player, world.multiworld)
    lTower = Region("Lightning Tower", world.player, world.multiworld)
    zJungle = Region("Zulon Jungle", world.player, world.multiworld)
    nLake = Region("Nalao Lake", world.player, world.multiworld)
    aForge = Region("Ancestral Forge", world.player, world.multiworld)
    mStarscape = Region("Magma Starscape", world.player, world.multiworld)
    dPoint = Region("Diamond Point", world.player, world.multiworld)
    gBubble = Region("Gravity Bubble", world.player, world.multiworld)
    bChase = Region("Bakunawa Chase", world.player, world.multiworld)
    bRush = Region("Bakunawa Rush", world.player, world.multiworld)
    rRoom = Region("Refinery Room", world.player, world.multiworld)
    cArboretum = Region("Clockwork Arboretum", world.player, world.multiworld)
    iDynamo = Region("Inversion Dynamo", world.player, world.multiworld)
    lCannon = Region("Lunar Cannon", world.player, world.multiworld)
    merga = Region("Merga", world.player, world.multiworld)
    wCore = Region("Weapon's Core", world.player, world.multiworld)
    
    # Add the menu and stage regions to our list of regions.
    regions = [menu, dValley, sPark, tFalls, rGraveyard, sArmory, snowfields, aMuseum, aSigwada, pHighway, zLand, battlesphere, gOpera1, gOpera2, auditorium, pCourtyard, tGate, sBridge, lTower, zJungle, nLake, aForge, mStarscape, dPoint, gBubble, bChase, bRush, rRoom, cArboretum, iDynamo, lCannon, merga, wCore]

    # Create and add the chest regions if the Chests option is enabled.
    if world.options.chests:
        regions.append(Region("Dragon Valley Chests", world.player, world.multiworld))
        regions.append(Region("Shenlin Park Chests", world.player, world.multiworld))
        regions.append(Region("Tiger Falls Chests", world.player, world.multiworld))
        regions.append(Region("Robot Graveyard Chests", world.player, world.multiworld))
        regions.append(Region("Shade Armory Chests", world.player, world.multiworld))
        regions.append(Region("Avian Museum Chests", world.player, world.multiworld))
        regions.append(Region("Airship Sigwada Chests", world.player, world.multiworld))
        regions.append(Region("Phoenix Highway Chests", world.player, world.multiworld))
        regions.append(Region("Zao Land Chests", world.player, world.multiworld))
        regions.append(Region("Globe Opera 1 Chests", world.player, world.multiworld))
        regions.append(Region("Globe Opera 2 Chests", world.player, world.multiworld))
        regions.append(Region("Palace Courtyard Chests", world.player, world.multiworld))
        regions.append(Region("Tidal Gate Chests", world.player, world.multiworld))
        regions.append(Region("Sky Bridge Chests", world.player, world.multiworld))
        regions.append(Region("Lightning Tower Chests", world.player, world.multiworld))
        regions.append(Region("Zulon Jungle Chests", world.player, world.multiworld))
        regions.append(Region("Nalao Lake Chests", world.player, world.multiworld))
        regions.append(Region("Ancestral Forge Chests", world.player, world.multiworld))
        regions.append(Region("Magma Starscape Chests", world.player, world.multiworld))
        regions.append(Region("Gravity Bubble Chests", world.player, world.multiworld))
        regions.append(Region("Bakunawa Rush Chests", world.player, world.multiworld))
        regions.append(Region("Clockwork Arboretum Chests", world.player, world.multiworld))
        regions.append(Region("Inversion Dynamo Chests", world.player, world.multiworld))
        regions.append(Region("Lunar Cannon Chests", world.player, world.multiworld))
        
    # Create and add the item box regions if the Item Box Sanity option is enabled.
    if world.options.item_boxes:
        regions.append(Region("Dragon Valley Item Boxes", world.player, world.multiworld))
        regions.append(Region("Shenlin Park Item Boxes", world.player, world.multiworld))
        regions.append(Region("Tiger Falls Item Boxes", world.player, world.multiworld))
        regions.append(Region("Robot Graveyard Item Boxes", world.player, world.multiworld))
        regions.append(Region("Shade Armory Item Boxes", world.player, world.multiworld))
        regions.append(Region("Snowfields Item Boxes", world.player, world.multiworld))
        regions.append(Region("Avian Museum Item Boxes", world.player, world.multiworld))
        regions.append(Region("Airship Sigwada Item Boxes", world.player, world.multiworld))
        regions.append(Region("Phoenix Highway Item Boxes", world.player, world.multiworld))
        regions.append(Region("Zao Land Item Boxes", world.player, world.multiworld))
        regions.append(Region("Globe Opera 1 Item Boxes", world.player, world.multiworld))
        regions.append(Region("Globe Opera 2 Item Boxes", world.player, world.multiworld))
        regions.append(Region("Palace Courtyard Item Boxes", world.player, world.multiworld))
        regions.append(Region("Tidal Gate Item Boxes", world.player, world.multiworld))
        regions.append(Region("Sky Bridge Item Boxes", world.player, world.multiworld))
        regions.append(Region("Lightning Tower Item Boxes", world.player, world.multiworld))
        regions.append(Region("Zulon Jungle Item Boxes", world.player, world.multiworld))
        regions.append(Region("Nalao Lake Item Boxes", world.player, world.multiworld))
        regions.append(Region("Ancestral Forge Item Boxes", world.player, world.multiworld))
        regions.append(Region("Magma Starscape Item Boxes", world.player, world.multiworld))
        regions.append(Region("Gravity Bubble Item Boxes", world.player, world.multiworld))
        regions.append(Region("Bakunawa Rush Item Boxes", world.player, world.multiworld))
        regions.append(Region("Clockwork Arboretum Item Boxes", world.player, world.multiworld))
        regions.append(Region("Inversion Dynamo Item Boxes", world.player, world.multiworld))
        regions.append(Region("Lunar Cannon Item Boxes", world.player, world.multiworld))
        regions.append(Region("Battlesphere Item Boxes", world.player, world.multiworld))
        
    # Create and add the shop, enemy sanity and boss sanity regions if their respective options are enabled.
    if world.options.milla_shop: regions.append(Region("Milla Shop", world.player, world.multiworld))
    if world.options.vinyl_shop: regions.append(Region("Vinyl Shop", world.player, world.multiworld))
    if world.options.enemies: regions.append(Region("Enemy", world.player, world.multiworld))
    if world.options.bosses: regions.append(Region("Boss", world.player, world.multiworld))

    # Add our regions to the world.
    world.multiworld.regions += regions


def connect_regions(world: FP2World) -> None:
    # Get the menu and stage regions.
    menu = world.get_region("Menu")
    dValley = world.get_region("Dragon Valley")
    sPark = world.get_region("Shenlin Park")
    tFalls = world.get_region("Tiger Falls")
    rGraveyard = world.get_region("Robot Graveyard")
    sArmory = world.get_region("Shade Armory")
    snowfields = world.get_region("Snowfields")
    aMuseum = world.get_region("Avian Museum")
    aSigwada = world.get_region("Airship Sigwada")
    pHighway = world.get_region("Phoenix Highway")
    zLand = world.get_region("Zao Land")
    battlesphere = world.get_region("The Battlesphere")
    gOpera1 = world.get_region("Globe Opera 1")
    gOpera2 = world.get_region("Globe Opera 2")
    auditorium = world.get_region("Auditorium")
    pCourtyard = world.get_region("Palace Courtyard")
    tGate = world.get_region("Tidal Gate")
    sBridge = world.get_region("Sky Bridge")
    lTower = world.get_region("Lightning Tower")
    zJungle = world.get_region("Zulon Jungle")
    nLake = world.get_region("Nalao Lake")
    aForge = world.get_region("Ancestral Forge")
    mStarscape = world.get_region("Magma Starscape")
    dPoint = world.get_region("Diamond Point")
    gBubble = world.get_region("Gravity Bubble")
    bChase = world.get_region("Bakunawa Chase")
    bRush = world.get_region("Bakunawa Rush")
    rRoom = world.get_region("Refinery Room")
    cArboretum = world.get_region("Clockwork Arboretum")
    iDynamo = world.get_region("Inversion Dynamo")
    lCannon = world.get_region("Lunar Cannon")
    merga = world.get_region("Merga")
    wCore = world.get_region("Weapon's Core")

    # Connect the stage regions to the menu region.
    menu.connect(dValley, "Menu to Dragon Valley")
    menu.connect(sPark, "Menu to Shenlin Park")
    menu.connect(tFalls, "Menu to Tiger Falls")
    menu.connect(rGraveyard, "Menu to Robot Graveyard")
    menu.connect(sArmory, "Menu to Shade Armory")
    menu.connect(snowfields, "Menu to Snowfields")
    menu.connect(aMuseum, "Menu to Avian Museum")
    menu.connect(aSigwada, "Menu to Airship Sigwada")
    menu.connect(pHighway, "Menu to Phoenix Highway")
    menu.connect(zLand, "Menu to Zao Land")
    menu.connect(battlesphere, "Menu to The Battlesphere")
    menu.connect(gOpera1, "Menu to Globe Opera 1")
    menu.connect(gOpera2, "Menu to Globe Opera 2")
    menu.connect(auditorium, "Menu to Auditorium")
    menu.connect(pCourtyard, "Menu to Palace Courtyard")
    menu.connect(tGate, "Menu to Tidal Gate")
    menu.connect(sBridge, "Menu to Sky Bridge")
    menu.connect(lTower, "Menu to Lightning Tower")
    menu.connect(zJungle, "Menu to Zulon Jungle")
    menu.connect(nLake, "Menu to Nalao Lake")
    menu.connect(aForge, "Menu to Ancestral Forge")
    menu.connect(mStarscape, "Menu to Magma Starscape")
    menu.connect(dPoint, "Menu to Diamond Point")
    menu.connect(gBubble, "Menu to Gravity Bubble")
    menu.connect(bChase, "Menu to Bakunawa Chase")
    menu.connect(bRush, "Menu to Bakunawa Rush")
    menu.connect(rRoom, "Menu to Refinery Room")
    menu.connect(cArboretum, "Menu to Clockwork Arboretum")
    menu.connect(iDynamo, "Menu to Inversion Dynamo")
    menu.connect(lCannon, "Menu to Lunar Cannon")
    menu.connect(merga, "Menu to Merga")
    menu.connect(wCore, "Menu to Weapon's Core")

    # Connect the chest regions to their approriate stage regions if the Chests option is enabled.
    if world.options.chests:
        dValley.connect(world.get_region("Dragon Valley Chests"), "Dragon Valley Chest Inclusion")
        sPark.connect(world.get_region("Shenlin Park Chests"), "Shenlin Park Chest Inclusion")
        tFalls.connect(world.get_region("Tiger Falls Chests"), "Tiger Falls Chest Inclusion")
        rGraveyard.connect(world.get_region("Robot Graveyard Chests"), "Robot Graveyard Chest Inclusion")
        sArmory.connect(world.get_region("Shade Armory Chests"), "Shade Armory Chest Inclusion")
        aMuseum.connect(world.get_region("Avian Museum Chests"), "Avian Museum Chest Inclusion")
        aSigwada.connect(world.get_region("Airship Sigwada Chests"), "Airship Sigwada Chest Inclusion")
        pHighway.connect(world.get_region("Phoenix Highway Chests"), "Phoenix Highway Chest Inclusion")
        zLand.connect(world.get_region("Zao Land Chests"), "Zao Land Chest Inclusion")
        gOpera1.connect(world.get_region("Globe Opera 1 Chests"), "Globe Opera 1 Chest Inclusion")
        gOpera2.connect(world.get_region("Globe Opera 2 Chests"), "Globe Opera 2 Chest Inclusion")
        pCourtyard.connect(world.get_region("Palace Courtyard Chests"), "Palace Courtyard Chest Inclusion")
        tGate.connect(world.get_region("Tidal Gate Chests"), "Tidal Gate Chest Inclusion")
        sBridge.connect(world.get_region("Sky Bridge Chests"), "Sky Bridge Chest Inclusion")
        lTower.connect(world.get_region("Lightning Tower Chests"), "Lightning Tower Chest Inclusion")
        zJungle.connect(world.get_region("Zulon Jungle Chests"), "Zulon Jungle Chest Inclusion")
        nLake.connect(world.get_region("Nalao Lake Chests"), "Nalao Lake Chest Inclusion")
        aForge.connect(world.get_region("Ancestral Forge Chests"), "Ancestral Forge Chest Inclusion")
        mStarscape.connect(world.get_region("Magma Starscape Chests"), "Magma Starscape Chest Inclusion")
        gBubble.connect(world.get_region("Gravity Bubble Chests"), "Gravity Bubble Chest Inclusion")
        bRush.connect(world.get_region("Bakunawa Rush Chests"), "Bakunawa Rush Chest Inclusion")
        cArboretum.connect(world.get_region("Clockwork Arboretum Chests"), "Clockwork Arboretum Chest Inclusion")
        iDynamo.connect(world.get_region("Inversion Dynamo Chests"), "Inversion Dynamo Chest Inclusion")
        lCannon.connect(world.get_region("Lunar Cannon Chests"), "Lunar Cannon Chest Inclusion")
        
    # Connect the Item Box regions to their approriate stage regions if the Item Box Sanity option is enabled.
    if world.options.item_boxes:
        dValley.connect(world.get_region("Dragon Valley Item Boxes"), "Dragon Valley Item Box Inclusion")
        sPark.connect(world.get_region("Shenlin Park Item Boxes"), "Shenlin Park Item Box Inclusion")
        tFalls.connect(world.get_region("Tiger Falls Item Boxes"), "Tiger Falls Item Box Inclusion")
        rGraveyard.connect(world.get_region("Robot Graveyard Item Boxes"), "Robot Graveyard Item Box Inclusion")
        sArmory.connect(world.get_region("Shade Armory Item Boxes"), "Shade Armory Item Box Inclusion")
        snowfields.connect(world.get_region("Snowfields Item Boxes"), "Snowfields Item Box Inclusion")
        aMuseum.connect(world.get_region("Avian Museum Item Boxes"), "Avian Museum Item Box Inclusion")
        aSigwada.connect(world.get_region("Airship Sigwada Item Boxes"), "Airship Sigwada Item Box Inclusion")
        pHighway.connect(world.get_region("Phoenix Highway Item Boxes"), "Phoenix Highway Item Box Inclusion")
        zLand.connect(world.get_region("Zao Land Item Boxes"), "Zao Land Item Box Inclusion")
        gOpera1.connect(world.get_region("Globe Opera 1 Item Boxes"), "Globe Opera 1 Item Box Inclusion")
        gOpera2.connect(world.get_region("Globe Opera 2 Item Boxes"), "Globe Opera 2 Item Box Inclusion")
        pCourtyard.connect(world.get_region("Palace Courtyard Item Boxes"), "Palace Courtyard Item Box Inclusion")
        tGate.connect(world.get_region("Tidal Gate Item Boxes"), "Tidal Gate Item Box Inclusion")
        sBridge.connect(world.get_region("Sky Bridge Item Boxes"), "Sky Bridge Item Box Inclusion")
        lTower.connect(world.get_region("Lightning Tower Item Boxes"), "Lightning Tower Item Box Inclusion")
        zJungle.connect(world.get_region("Zulon Jungle Item Boxes"), "Zulon Jungle Item Box Inclusion")
        nLake.connect(world.get_region("Nalao Lake Item Boxes"), "Nalao Lake Item Box Inclusion")
        aForge.connect(world.get_region("Ancestral Forge Item Boxes"), "Ancestral Forge Item Box Inclusion")
        mStarscape.connect(world.get_region("Magma Starscape Item Boxes"), "Magma Starscape Item Box Inclusion")
        gBubble.connect(world.get_region("Gravity Bubble Item Boxes"), "Gravity Bubble Item Box Inclusion")
        bRush.connect(world.get_region("Bakunawa Rush Item Boxes"), "Bakunawa Rush Item Box Inclusion")
        cArboretum.connect(world.get_region("Clockwork Arboretum Item Boxes"), "Clockwork Arboretum Item Box Inclusion")
        iDynamo.connect(world.get_region("Inversion Dynamo Item Boxes"), "Inversion Dynamo Item Box Inclusion")
        lCannon.connect(world.get_region("Lunar Cannon Item Boxes"), "Lunar Cannon Item Box Inclusion")
        battlesphere.connect(world.get_region("Battlesphere Item Boxes"), "Battlesphere Item Box Inclusion")
        
    # Connect the shop, enemy sanity and boss sanity regions to the menu if their respective options are enabled.
    if world.options.milla_shop: menu.connect(world.get_region("Milla Shop"), "Milla Shop Inclusion")
    if world.options.vinyl_shop: menu.connect(world.get_region("Vinyl Shop"), "Vinyl Shop Inclusion")
    if world.options.enemies: menu.connect(world.get_region("Enemy"), "Enemysanity Inclusion")
    if world.options.bosses: menu.connect(world.get_region("Boss"), "Bosssanity Inclusion")